### ISSUE TITLE
Probably missing "decodeEntities" in using cheerio

### ISSUE THREAD

**Issue by jiyinyiyong** [jonkemp/style-data#2]
May cause problem loading Chinese: https://github.com/cheeriojs/cheerio/issues/565

https://github.com/jonkemp/style-data/blob/master/index.js#L8
Also https://github.com/jonkemp/list-stylesheets/blob/master/index.js#L7

**Comment by jonkemp** [comment]
What's the issue?

**Comment by jiyinyiyong** [comment]
@jonkemp My teammate was using the gulp-inline-css and found problems in transforming HTML with Chinese inside, and we looked into that and fixed by specifying `decodeEntities` in calling `cheerio`.

@SuneBear may need to add his example here...

**Comment by SuneBear** [comment]
Thank you for your attention.
I found the problem was caused by non-ascii Unicode escape.

Before the transfer: 
```
<!DOCTYPE html>
<html>
<head>
<title>Unicode escape test ★㏒√</title>
<link inline rel="stylesheet" href="style.css">
</head>
<body>

<div class="markdown-bg">
  <div class="markdown-body">
    <p>Example text 测试文本</p>
   </div>
</div>

</body>
</html>
```

After the transfer: 
```
<!DOCTYPE html>
<html>
<head>
<title>Unicode escape test &#x2605;&#x33D2;&#x221A;</title>
<style>
@media (min-width: 768px) {
  .markdown-bg {
    background: #f5f5f5;
    padding: 30px 0;
  }
  .markdown-body {
    padding: 30px !important;
  }
}

@media (max-width: 840px) {
  .markdown-body {
    max-width: 680px !important;
  }
}
</style>
</head>
<body>

<div class="markdown-bg">
  <div class="markdown-body" style="-moz-osx-font-smoothing: grayscale; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; background: #FFFFFF; color: #333333; font-family: 'Helvetica Neue', Helvetica, 'Segoe UI', Arial, freesans, sans-serif; font-size: 16px; line-height: 1.6; margin: 0 auto; max-width: 720px; overflow: hidden; padding: 5px; padding-bottom: 10px; text-rendering: optimizeLegibility; word-wrap: break-word;">
    <p style="-moz-box-sizing: border-box; box-sizing: border-box; margin-bottom: 0; margin-top: 0;">Example text &#x6D4B;&#x8BD5;&#x6587;&#x672C;</p>
   </div>
</div>

</body>
</html>
```
I can't understand why cheerio default escape and 
hope you could set decodeEntities to false.

Best Regards : )

**Comment by jonkemp** [comment]
I have updated both modules, so closing this now. Thanks!

**Comment by crapthings** [comment]
which modules ?

i still get these after set decodeEntities to false.

I20150411-14:34:26.724(8)?
I20150411-14:34:26.724(8)? ����Ժ���ߴ����᣺���ز�Ͷ����������8%
I20150411-14:34:26.724(8)?
I20150411-14:34:26.725(8)? 75�����з���2014�긺ծ�ϼƽӽ�1.95����Ԫ
I20150411-14:34:26.725(8)?
I20150411-14:34:26.726(8)? ������β¥�ų����� "�����˰�"һ�ȶ���82��
I20150411-14:34:26.727(8)?
I20150411-14:34:26.727(8)? ¥������Ӧ��"�¸�ʮ��"
I20150411-14:34:26.727(8)?
I20150411-14:34:26.727(8)? ����ת��������������
I20150411-14:34:26.728(8)?
I20150411-14:34:26.728(8)? ����¥�������Ǽ�
I20150411-14:34:26.728(8)?
I20150411-14:34:26.729(8)? "һ��һ·"������ɳ����
I20150411-14:34:26.730(8)?
I20150411-14:34:26.730(8)? ��ĩ���깺�������Ŷ����� ��Щ���ǻ�
I20150411-14:34:26.730(8)?
I20150411-14:34:26.731(8)? �����򷿲��޹���Ԣ������ �׸�����20����
I20150411-14:34:26.731(8)?
I20150411-14:34:26.731(8)? ����:����ҵ���鲻ȷ�������� ���Ʋ�����
I20150411-14:34:26.732(8)?
I20150411-14:34:26.732(8)? �����Է����ϱ�������
I20150411-14:34:26.732(8)?
I20150411-14:34:26.785(8)? ����ת��������������

**Comment by jonkemp** [comment]
@crapthings `style-data` and `list-stylesheets`

**Comment by crapthings** [comment]
the site that use gbk encode, how do i convert it?

**Comment by jonkemp** [comment]
@crapthings I don't know
